(""
 ("Warnings when not enough directories"
  (let ((my-caches::*hierarchical-caches* nil))
    (handler-case (define-hierarchical-cache "cache-example" (nil
                                                              :alphas (t))
                                             :alphas (concatenate 'string "result: " alpha-name)
                                             :root (list "alpha1" "alpha2"))
      (warning (w) (string= (format nil "~a" w)
                            "No output directory defined while as much as one preformatter is defined."))
      (condition (c) nil)
      (:no-error (r) nil)))
  (let ((my-caches::*hierarchical-caches* nil))
    (handler-case (define-hierarchical-cache "cache-example" (nil
                                                              :root (("root-file" t) ("test-file" t))
                                                              :alphas (t))
                                             :alphas (concatenate 'string "result: " alpha-name)
                                             :root (list "alpha1" "alpha2"))
      (warning (w) (string= (format nil "~a" w)
                            "No output directory defined while as much as two preformatters are defined."))
      (condition (c) nil)
      (:no-error (r) nil))))
 ("Warning when not enough preformatters"
  (let ((my-caches::*hierarchical-caches* nil))
    (handler-case (define-hierarchical-cache "cache-example" (((usage-temporary-directory))
                                                              :alphas)
                                             :alphas (concatenate 'string "result: " alpha-name)
                                             :root (list "alpha1" "alpha2"))
      (warning (w) (string= (format nil "~a" w)
                            "No preformatter defined while one directory is defined."))
      (condition (c) nil)
      (:no-error (r) nil)))
  (let ((my-caches::*hierarchical-caches* nil))
    (handler-case (define-hierarchical-cache "cache-example" (((usage-temporary-directory)
                                                               (usage-temporary-directory))
                                                              :root (("root-file" t))
                                                              :alphas)
                                             :alphas (concatenate 'string "result: " alpha-name)
                                             :root (list "alpha1" "alpha2"))
      (warning (w) (string= (format nil "~a" w)
                            "Only as much as one preformatter defined while two directories are defined."))
      (condition (c) nil)
      (:no-error (r) nil)))))