("once-only prevent multiple evaluations of a form. Indispensable when such a form has side-effect."
 ("Multiple evaluations with no side-effect"
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        `(* ,nb ,nb)))
             (square (1+ x))))
         100)
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        (once-only (nb)
                                   `(* ,nb ,nb))))
             (square (1+ x))))
         100))
 ("Multiple evaluations with a side-effect"
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        `(* ,nb ,nb)))
             (square (incf x))))
         110)
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        `(* ,nb ,nb)))
             (square (incf x))
             x))
         11)
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        (once-only (nb)
                                   `(* ,nb ,nb))))
             (square (incf x))))
         100)
  (equal (let ((x 9))
           (macrolet ((square (nb)
                        (once-only (nb)
                                   `(* ,nb ,nb))))
             (square (incf x))
             x))
         10)))